language: node_js
node_js:
  - 5.0
notifications:
  email:
    - mattos.michel@gmail.com
env:
  global:
    - NODE_ENV: test
addons:
  sauce_connect: true
before_install:
  - npm install -g npm
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g karma-cli
  - npm install -g protractor
  - webdriver-manager update
  - bower install
before_script:
  - node test/data.js
  - grunt
  - cd dist
script:
  - karma start config/karma.config.js --single-run --browsers PhantomJS
  - node server &
  - protractor config/protractor.js
services:
  - mongodb
